### ISSUE TITLE
No examples.

### ISSUE THREAD

**Issue by Arcanorum** [TuurDutoit/crash#2]
There are 0 examples of this being used.

**Comment by TuurDutoit** [comment]
I know, and I'm not planning on adding any, because I'm not really working on this anymore. It is pretty stable by now, feel free to use it, and if you run into issues I'll be happy to help solve them. But I'm not going to spend my time writing examples for code I'm not actively working on. Feel free to send me pull request though!

**Comment by Arcanorum** [comment]
Just to clarify. If I don't insert a collider into RBush, then I can do `delete myCollider` to delete the reference to a collider and the collider object will be safely picked up by the GC?
The collider isn't fed into any other other systems that keep a reference to it?

**Comment by TuurDutoit** [comment]
If you don't add it to crash (which in turn adds it to rbush), or you remove it after inserting, no reference should be kept, so the GC should pick it up, yes. It's been a while since I worked on the code, so I'm not 100% sure, but I don't see any reason to keep a reference.

May I add that `delete` is pretty much a no-no in Javascript: it does the same as `variable = undefined`, i.e. it doesn't *actually* delete the object from memory. The downside is that it dramatically drops the performance of objects when used on their properties, e.g. `delete myobject.myproperty`...
